spring:
  application:
    name: finance_backend
  datasource:
    url: jdbc:mysql://localhost:3306/finance_backend
    username: root
    password: Lolownage00!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    file:
      name: logs/finance_backend.log
    level:
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

